#
# xAdminZone
# by lxckScream (https://spigotmc.ru/members/lxckscreamov.56306/)
#

# Локация админ зоны
admin-zone-location: world;0;100;0

# Настройка боссбара
bossbar:
  enabled: true
  text: "&6Админ-Зона &8| &7Вы находитесь в &6Админ-Зоне&7! В эту зону попасть игрокам невозможно."
  color: YELLOW

# Сообщения
messages:
  no-perms: "&cУ Вас нет прав на использование данной команды (Ошибка? - обратитесь к администратору сервера)"